server:
  port: 7777

---
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/car_repair_shop?currentSchema=develop
    username: postgres
    password: postgres
  flyway:
    default-schema: develop

---

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/car_repair_shop?currentSchema=production
    username: postgres
    password: postgres
  flyway:
    default-schema: production
